import {
	SoftwareTechnologyOption,
	SoftwareTechnologyOptionType,
} from '@/lib/types';

export const SoftwareTechnologiesData: SoftwareTechnologyOptionType[] =
	[
		{
			type: SoftwareTechnologyOption.NEXTJS,
			title: 'Next.js',
			iconUrl: '/images/software-technologies/nextjs.png',
			link: 'https://nextjs.org/',
		},
		{
			type: SoftwareTechnologyOption.REACT,
			title: 'React.js',
			iconUrl: '/images/software-technologies/react.png',
			link: 'https://react.dev/',
		},
		{
			type: SoftwareTechnologyOption.TAILWIND,
			title: 'Tailwind CSS',
			iconUrl: '/images/software-technologies/tailwind.png',
			link: 'https://tailwindcss.com/',
		},
		{
			type: SoftwareTechnologyOption.SHADCN,
			title: 'Shadcn',
			iconUrl: '/images/software-technologies/shadcn.png',
			link: 'https://ui.shadcn.com/',
		},
		{
			type: SoftwareTechnologyOption.STRIPE,
			title: 'Stripe',
			iconUrl: '/images/software-technologies/stripe.png',
			link: 'https://stripe.com/',
		},
		{
			type: SoftwareTechnologyOption.OPENAI,
			title: 'OpenAI',
			iconUrl: '/images/software-technologies/openai.png',
			link: 'https://openai.com/',
		},
		{
			type: SoftwareTechnologyOption.GROQ,
			title: 'Groq',
			iconUrl: '/images/software-technologies/groq.png',
			link: 'https://groq.com/',
		},
		{
			type: SoftwareTechnologyOption.CARTESIA,
			title: 'Cartesia',
			iconUrl: '/images/software-technologies/cartesia.png',
			link: 'https://cartesia.ai/',
		},
		{
			type: SoftwareTechnologyOption.DENO,
			title: 'Deno',
			iconUrl: '/images/software-technologies/deno.svg',
			link: 'https://deno.com/',
		},
		{
			type: SoftwareTechnologyOption.PINECONE,
			title: 'Pinecone',
			iconUrl: '/images/software-technologies/pinecone.png',
			link: 'https://pinecone.io/',
		},
		{
			type: SoftwareTechnologyOption.SUPABASE,
			title: 'Supabase',
			iconUrl: '/images/software-technologies/supabase.png',
			link: 'https://supabase.com/',
		},
		{
			type: SoftwareTechnologyOption.SAMBANOVA,
			title: 'SambaNova',
			iconUrl: '/images/software-technologies/sambanova.png',
			link: 'https://sambanova.ai/',
		},
		{
			type: SoftwareTechnologyOption.LLAMA,
			title: 'Llama',
			iconUrl: '/images/software-technologies/meta.png',
			link: 'https://llama.meta.com/',
		},
		{
			type: SoftwareTechnologyOption.REACT_NATIVE,
			title: 'React Native',
			iconUrl: '/images/software-technologies/react.png',
			link: 'https://reactnative.dev/',
		},
		{
			type: SoftwareTechnologyOption.POSTGRESQL,
			title: 'PostgreSQL',
			iconUrl: '/images/software-technologies/postgresql.png',
			link: 'https://www.postgresql.org/',
		},
		{
			type: SoftwareTechnologyOption.IONIC,
			title: 'Ionic',
			iconUrl: '/images/software-technologies/ionic.png',
			link: 'https://ionicframework.com/',
		},
		{
			type: SoftwareTechnologyOption.CAPACITOR,
			title: 'Capacitor',
			iconUrl: '/images/software-technologies/capacitor.png',
			link: 'https://capacitorjs.com/',
		},
		{
			type: SoftwareTechnologyOption.EXPO,
			title: 'Expo',
			iconUrl: '/images/software-technologies/expo.svg',
			link: 'https://expo.dev/',
		},
		{
			type: SoftwareTechnologyOption.FIREBASE,
			title: 'Firebase',
			iconUrl: '/images/software-technologies/firebase.png',
			link: 'https://firebase.google.com/',
		},
		{
			type: SoftwareTechnologyOption.TWILIO,
			title: 'Twilio',
			iconUrl: '/images/software-technologies/twilio.png',
			link: 'https://www.twilio.com/',
		},
		{
			type: SoftwareTechnologyOption.SWIFT,
			title: 'Swift',
			iconUrl: '/images/software-technologies/swift.png',
			link: 'https://developer.apple.com/swift/',
		},
		{
			type: SoftwareTechnologyOption.NODE,
			title: 'Node.js',
			iconUrl: '/images/software-technologies/node.png',
			link: 'https://nodejs.org/',
		},
		{
			type: SoftwareTechnologyOption.GOOGLE_MAPS,
			title: 'Google Maps',
			iconUrl: '/images/software-technologies/google-maps.png',
			link: 'https://www.google.com/maps',
		},
		{
			type: SoftwareTechnologyOption.COCOAPODS,
			title: 'CocoaPods',
			iconUrl: '/images/software-technologies/cocoapods.png',
			link: 'https://cocoapods.org/',
		},
		{
			type: SoftwareTechnologyOption.OBJECTIVE_C,
			title: 'Objective-C',
			iconUrl: '/images/software-technologies/apple.png',
			link: 'https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html',
		},
		{
			type: SoftwareTechnologyOption.RASPBERRY_PI,
			title: 'Raspberry Pi',
			iconUrl: '/images/software-technologies/raspberry-pi.png',
			link: 'https://www.raspberrypi.org/',
		},
		{
			type: SoftwareTechnologyOption.VUE,
			title: 'Vue.js',
			iconUrl: '/images/software-technologies/vuejs.png',
			link: 'https://vuejs.org/',
		},
		{
			type: SoftwareTechnologyOption.MONGODB,
			title: 'MongoDB',
			iconUrl: '/images/software-technologies/mongodb.svg',
			link: 'https://www.mongodb.com/',
		},
		{
			type: SoftwareTechnologyOption.BBME,
			title: 'BBM-e',
			iconUrl: '/images/software-technologies/bbme.png',
			link: 'https://www.blackberry.com/us/en/products/bbm-enterprise',
		},
		{
			type: SoftwareTechnologyOption.IRIDIUM,
			title: 'Iridium',
			iconUrl: '/images/software-technologies/iridium.png',
			link: 'https://www.iridium.com/',
		},
		{
			type: SoftwareTechnologyOption.ARDUINO,
			title: 'Arduino',
			iconUrl: '/images/software-technologies/arduino.png',
			link: 'https://www.arduino.cc/',
		},
		{
			type: SoftwareTechnologyOption.ESP32,
			title: 'ESP32',
			iconUrl: '/images/software-technologies/espressif.png',
			link: 'https://www.espressif.com/en/products/socs/esp32',
		},
		{
			type: SoftwareTechnologyOption.NORDIC_SDK,
			title: 'Nordic SDK',
			iconUrl: '/images/software-technologies/nordic.png',
			link: 'https://www.nordicsemi.com/Software-and-tools/Software/nRF-Connect-SDK',
		},
		{
			type: SoftwareTechnologyOption.CPP,
			title: 'C/C++',
			iconUrl: '/images/software-technologies/cpp.png',
			link: 'https://isocpp.org/',
		},
		{
			type: SoftwareTechnologyOption.ZEPHYR,
			title: 'Zephyr',
			iconUrl: '/images/software-technologies/zephyr.svg',
			link: 'https://zephyrproject.org/',
		},
		{
			type: SoftwareTechnologyOption.ALTIUM,
			title: 'Altium Designer',
			iconUrl:
				'/images/software-technologies/altium-designer.png',
			link: 'https://www.altium.com/products/altium-designer',
		},
		{
			type: SoftwareTechnologyOption.SEGGER,
			title: 'SEGGER SES',
			iconUrl: '/images/software-technologies/segger.png',
			link: 'https://www.segger.com/',
		},
		{
			type: SoftwareTechnologyOption.FUSION,
			title: 'Fusion 360',
			iconUrl: '/images/software-technologies/fusion.png',
			link: 'https://www.autodesk.com/products/fusion-360/overview',
		},
		{
			type: SoftwareTechnologyOption.PARTICLE,
			title: 'Particle',
			iconUrl: '/images/software-technologies/particle.png',
			link: 'https://www.particle.io/',
		},
		{
			type: SoftwareTechnologyOption.MAPBOX,
			title: 'Mapbox',
			iconUrl: '/images/software-technologies/mapbox.png',
			link: 'https://www.mapbox.com/',
		},
	];
