import { TechnologyPage } from '@/lib/types';
import { Cpu, MemoryStick, CodeXml, Frame } from 'lucide-react';

export const TechnologiesOptions: TechnologyPage[] = [
	{
		title: 'Hardware',
		description: 'Hardware',
		icon: <Cpu size={16} color="#ffffff" />,
		groups: [
			{
				title: 'MCUs',
				description: 'Microcontrollers used ',
				technologies: [
					{
						title: 'nRF 52840, 52832, 51822, 51422',
						description: 'Nordic Semiconductor',
						iconUrl: '/images/nrf52840.png',
						link: 'https://www.intel.com',
						workExperienceIds: ['eigen-fitness'],
						startYear: 2022,
					},
					{
						title: 'ATMEGA328P',
						description: 'Atmel',
						iconUrl: '/images/nrf52840.png',
						link: 'https://www.intel.com',
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
						],
						startYear: 2022,
					},
					{
						title: 'CC2650',
						description: 'Texas Instruments',
						iconUrl: '/images/nrf52840.png',
						link: 'https://www.intel.com',
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
						],
						startYear: 2022,
					},
					{
						title: 'DA14580',
						description: 'Dialog Semiconductor',
						iconUrl: '/images/silicon-labs.png',
						link: 'https://www.intel.com',
						workExperienceIds: ['eigen-fitness'],
						startYear: 2022,
					},
					{
						title: 'STM32F205',
						description: 'STMicroelectronics',
						iconUrl: '/images/silicon-labs.png',
						link: 'https://www.intel.com',
						workExperienceIds: ['exact-technology'],
						startYear: 2022,
					},
					{
						title: '68HC11',
						description: 'Motorola',
						iconUrl: '/images/nrf52840.png',
						link: 'https://www.intel.com',
						workExperienceIds: ['eigen-fitness'],
						startYear: 2022,
					},
				],
			},
			{
				title: 'Wireless Communication',
				description: 'Microcontrollers used ',
				technologies: [
					{
						title: 'Bluetooth Low Energy',
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
						],
						startYear: 2022,
					},
					{
						title: 'LoRa & LoRaWAN',
						workExperienceIds: ['exact-technology'],
						startYear: 2022,
					},
					{
						title: '4G/LTE',
						workExperienceIds: ['exact-technology'],
						startYear: 2022,
					},
					{
						title: 'Satellite Communication',
						workExperienceIds: ['exact-technology'],
						startYear: 2022,
					},
					{
						title: 'OTA DFU (via BLE)',
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
						],
						startYear: 2022,
					},
				],
			},
			{
				title: 'Communication & Debugging',
				splitColumns: true,
				technologies: [
					{
						title: 'I2C',
						startYear: 2019,
					},
					{
						title: 'JTAG',
						startYear: 2012,
					},
					{
						title: 'SPI',
						startYear: 2012,
					},
					{
						title: 'SWD',
						startYear: 2012,
					},
					{
						title: 'USB',
						startYear: 2012,
					},
					{
						title: 'UART',
						startYear: 2012,
					},
					{
						title: 'PWM',
						startYear: 2019,
					},
					{
						title: '1-Wire',
						startYear: 2019,
					},
				],
			},
			{
				title: 'Circuit Design',
				splitColumns: true,
				technologies: [
					{
						title: 'Antenna Tuning',
						startYear: 2019,
					},
					{
						title: 'High-Densitiy PCB Design',
						startYear: 2019,
					},
					{
						title: 'Multi-Layer PCB Design',
						startYear: 2012,
					},
					{
						title: 'Ultra-low-power Design',
						startYear: 2012,
					},
					{
						title: 'LiPo/Li-Ion Battery Chargers',
						startYear: 2012,
					},
					{
						title: '9-axis IMUs',
						startYear: 2012,
					},
					{
						title: '9-axis IMUs',
						startYear: 2012,
					},
					{
						title: 'DC-DC Converter Design',
						startYear: 2019,
					},
					{
						title: 'AC-DC Converter Design',
						startYear: 2019,
					},
					{
						title: 'Digital High-power Controllers',
						startYear: 2019,
					},
					{
						title: 'Signal Noise Suppression',
						startYear: 2019,
					},
				],
			},
			{
				title: 'Mechanical Design & Fabrication',
				technologies: [
					{
						title: 'Plastic Injection Molding Design',
						startYear: 2019,
					},
					{
						title: 'FDM 3D Printing',
						startYear: 2019,
					},
					{
						title: 'SLA 3D Printing',
						startYear: 2012,
					},
					{
						title: 'CNC Milling & Turning',
						startYear: 2012,
					},
					{
						title: 'Manual Vertical Milling',
						startYear: 2012,
					},
					{
						title: 'Laser Cutting Plastic',
						startYear: 2012,
					},
					{
						title: 'Harness Design & Management',
						startYear: 2012,
					},
				],
			},
			{
				title: 'CAD Software',
				splitColumns: true,
				technologies: [
					{
						title: 'Altium Designer',
						startYear: 2019,
					},
					{
						title: 'Altium Circuit Studio',
						startYear: 2012,
					},
					{
						title: 'Fusion 360',
						startYear: 2019,
					},
					{
						title: 'Eagle',
						startYear: 2012,
					},
				],
			},
			{
				title: 'Tools',
				splitColumns: true,
				technologies: [
					{
						title: 'Oscilloscope with FFT',
						startYear: 2015,
					},
					{
						title: 'Spectrum Analyzer',
						startYear: 2019,
					},
					{
						title: 'Logic Analyzer',
						startYear: 2017,
					},
					{
						title: 'DMM',
						startYear: 2012,
					},
					{
						title: 'Function Generator',
						startYear: 2012,
					},
					{
						title: 'JTAG Programmer',
						startYear: 2012,
					},
					{
						title: 'Reflow Soldering',
						startYear: 2012,
					},
					{
						title: 'Hand Soldering (SMT)',
						startYear: 2012,
					},
				],
			},
		],
	},
	{
		title: 'Firmware',
		description: 'Firmware',
		icon: <MemoryStick size={16} color="#ffffff" />,
		groups: [
			{
				title: 'Application Layer',
				technologies: [
					{
						title: 'Bare Metal C/C++',
						description: 'Bare Metal C/C++',
						iconUrl: '/images/zephyr.png',
						link: 'https://www.ami.com',
						startYear: 2022,
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
							'blackberry',
						],
					},
					{
						title: 'Zephyr',
						description: 'Zephyr',
						iconUrl: '/images/zephyr.png',
						link: 'https://www.ami.com',
						startYear: 2022,
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
						],
					},
					{
						title: 'FreeRTOS',
						description: 'FreeRTOS',
						iconUrl: '/images/freertos.png',
						link: 'https://www.ami.com',
						startYear: 2022,
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
						],
					},
					{
						title: 'Arduino & Processing',
						description: 'Arduino & Processing',
						iconUrl: '/images/zephyr.png',
						link: 'https://www.ami.com',
						startYear: 2022,
						workExperienceIds: [
							'eigen-fitness',
							'exact-technology',
							'blackberry',
						],
					},
				],
			},
			{
				title: 'Environments & Tools',
				technologies: [
					{
						title: 'SEGGER Embedded Studio',
						description: 'SEGGER Embedded Studio',
						iconUrl: '/images/zephyr.png',
						link: 'https://www.ami.com',
						startYear: 2022,
					},
					{
						title: 'SEGGER J-Link',
						description: 'SEGGER J-Link',
						iconUrl: '/images/freertos.png',
						link: 'https://www.ami.com',
						startYear: 2022,
					},
					{
						title: 'ARM Keil',
						description: 'SEGGER J-Link',
						iconUrl: '/images/freertos.png',
						link: 'https://www.ami.com',
						startYear: 2022,
					},
					{
						title: 'CCStudio',
						description: 'SEGGER J-Link',
						iconUrl: '/images/freertos.png',
						link: 'https://www.ami.com',
						startYear: 2022,
					},
					{
						title: 'SI Simplicity Studio',
						description: 'SI Simplicity Studio',
						iconUrl: '/images/freertos.png',
						link: 'https://www.ami.com',
						startYear: 2022,
					},
				],
			},
		],
	},
	{
		title: 'Software',
		description: 'Software',
		icon: <CodeXml size={16} color="#ffffff" />,
		groups: [
			{
				title: 'Languages, Frameworks, & Runtimes',
				description: 'Languages, Frameworks, & Runtimes',
				splitColumns: true,
				technologies: [
					{
						title: 'React',
						description: 'React',
						iconUrl: '/images/react.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
						yearsOfExperience: 5,
					},
					{
						title: 'React Native',
						description: 'React Native',
						iconUrl: '/images/react.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
						yearsOfExperience: 5,
					},
					{
						title: 'Vue',
						description: 'Vue',
						iconUrl: '/images/vue.png',
						link: 'https://www.vuejs.org',
						startYear: 2022,
						yearsOfExperience: 2,
					},
					{
						title: 'Next.js',
						description: 'Next.js',
						iconUrl: '/images/nextjs.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
						yearsOfExperience: 1,
					},
					{
						title: 'Swift & SwiftUI',
						description: 'Swift & SwiftUI',
						iconUrl: '/images/swift.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
						yearsOfExperience: 5,
					},
					{
						title: 'Python',
						description: 'Python',
						iconUrl: '/images/python.png',
						link: 'https://www.python.org',
						startYear: 2022,
						yearsOfExperience: 3,
					},
					{
						title: 'Node.js',
						description: 'Node.js',
						iconUrl: '/images/nodejs.png',
						link: 'https://www.nodejs.org',
						startYear: 2022,
						yearsOfExperience: 7,
					},
					{
						title: 'Express',
						description: 'Express',
						iconUrl: '/images/express.png',
						link: 'https://www.expressjs.org',
						startYear: 2022,
						yearsOfExperience: 7,
					},
					{
						title: 'Deno',
						description: 'Deno',
						iconUrl: '/images/deno.png',
						link: 'https://www.mongodb.com',
						startYear: 2022,
						yearsOfExperience: 1,
					},

					{
						title: 'Tailwind',
						description: 'Tailwind',
						iconUrl: '/images/tailwind.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
						yearsOfExperience: 5,
					},
				],
			},
			{
				title: 'Tools & Platforms',
				description: 'Tools & Platforms',
				splitColumns: true,
				technologies: [
					{
						title: 'AWS (EC2, S3, RDS, Lambda)',
						description: 'AWS (EC2, S3, RDS, Lambda)',
						iconUrl: '/images/aws.png',
						link: 'https://aws.amazon.com',
						startYear: 2022,
						yearsOfExperience: 3,
					},
					{
						title: 'Supabase',
						description: 'Supabase',
						iconUrl: '/images/supabase.png',
						link: 'https://supabase.com',
						startYear: 2022,
						yearsOfExperience: 2,
					},

					{
						title: 'Firebase',
						description: 'Firebase',
						iconUrl: '/images/firebase.png',
						link: 'https://supabase.com',
						startYear: 2022,
						yearsOfExperience: 7,
					},
					{
						title: 'Google Cloud (GCP)',
						description: 'Google Cloud (GCP)',
						iconUrl: '/images/gcp.png',
						link: 'https://cloud.google.com',
						startYear: 2022,
						yearsOfExperience: 2,
					},
					{
						title: 'Azure',
						description: 'Azure',
						iconUrl: '/images/azure.png',
						link: 'https://aws.amazon.com',
						startYear: 2022,
						yearsOfExperience: 1,
					},
					{
						title: 'GitHub',
						description: 'GitHub',
						iconUrl: '/images/github.png',
						link: 'https://www.github.com',
						startYear: 2022,
						yearsOfExperience: 10,
					},
					{
						title: 'Bitbucket',
						description: 'Bitbucket',
						iconUrl: '/images/bitbucket.png',
						link: 'https://www.bitbucket.org',
						startYear: 2022,
						yearsOfExperience: 10,
					},
					{
						title: 'Docker',
						description: 'Docker',
						iconUrl: '/images/docker.png',
						link: 'https://www.docker.com',
						startYear: 2022,
						yearsOfExperience: 2,
					},
					{
						title: 'Vercel',
						description: 'Vercel',
						iconUrl: '/images/vercel.png',
						link: 'https://www.vercel.com',
						startYear: 2022,
						yearsOfExperience: 2,
					},
					{
						title: 'Expo',
						description: 'Expo',
						iconUrl: '/images/expo.png',
						link: 'https://www.vercel.com',
						startYear: 2022,
						yearsOfExperience: 2,
					},
				],
			},
			{
				title: 'AI & ML',
				description: 'APIs & SDKs',
				splitColumns: true,
				technologies: [
					{
						title: 'Vector Databases',
						description: 'Vector Databases',
						iconUrl: '/images/stripe.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
						yearsOfExperience: 1,
					},
					{
						title: 'RAG',
						description: 'Vector Databases',
						iconUrl: '/images/stripe.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
						yearsOfExperience: 1,
					},
					{
						title: 'OpenAI API',
						description: 'OpenAI API',
						iconUrl: '/images/twilio.png',
						link: 'https://www.vuejs.org',
						startYear: 2022,
						yearsOfExperience: 2,
					},
					{
						title: 'Groq',
						description: 'Groq',
						iconUrl: '/images/mixpanel.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
						yearsOfExperience: 0.5,
					},
					{
						title: 'Cerebras',
						description: 'Cerebras',
						iconUrl: '/images/cerebras.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
						yearsOfExperience: 0.5,
					},
					{
						title: 'Llama',
						description: 'Llama',
						iconUrl: '/images/llama.png',
						link: 'https://www.nodejs.org',
						startYear: 2022,
					},
					{
						title: 'Tensorflow',
						description: 'Tensorflow',
						iconUrl: '/images/tensorflow.png',
						link: 'https://www.expressjs.org',
						startYear: 2022,
					},
					{
						title: 'Anthropic',
						description: 'Anthropic',
						iconUrl: '/images/anthropic.png',
						link: 'https://www.mongodb.com',
						startYear: 2022,
					},
					{
						title: 'Ollama',
						description: 'Anthropic',
						iconUrl: '/images/anthropic.png',
						link: 'https://www.mongodb.com',
						startYear: 2022,
					},
					{
						title: 'Hugging Face',
						description: 'Hugging Face',
						iconUrl: '/images/hugging-face.png',
						link: 'https://www.huggingface.co',
						startYear: 2022,
					},
				],
			},
			{
				title: 'Database',
				description: 'Database',
				splitColumns: true,
				technologies: [
					{
						title: 'PostgreSQL',
						description: 'PostgreSQL',
						iconUrl: '/images/postgresql.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
					},
					{
						title: 'NoSQL',
						description: 'NoSQL',
						iconUrl: '/images/mongodb.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
					},
					{
						title: 'MongoDB',
						description: 'MongoDB',
						iconUrl: '/images/mongodb.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
					},
					{
						title: 'Vector Databases',
						description: 'Cerebras',
						iconUrl: '/images/cerebras.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
					},
				],
			},
			{
				title: 'Authentication',
				description: 'Authentication',
				splitColumns: true,
				technologies: [
					{
						title: 'Supabase Auth',
						description: 'Supabase Auth',
						iconUrl: '/images/supabase.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
					},
					{
						title: 'Kinde',
						description: 'Kinde',
						iconUrl: '/images/kinde.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
					},
					{
						title: 'Firebase Auth',
						description: 'Firebase Auth',
						iconUrl: '/images/firebase.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
					},
					{
						title: 'Vector Databases',
						description: 'Cerebras',
						iconUrl: '/images/cerebras.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
					},
				],
			},
			{
				title: 'APIs, SDKs, & Libraries',
				description: 'APIs & SDKs',
				splitColumns: true,
				technologies: [
					{
						title: 'Stripe',
						description: 'Stripe',
						iconUrl: '/images/stripe.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
					},
					{
						title: 'Twilio',
						description: 'Twilio',
						iconUrl: '/images/twilio.png',
						link: 'https://www.vuejs.org',
						startYear: 2022,
					},
					{
						title: 'Mixpanel',
						description: 'Mixpanel',
						iconUrl: '/images/mixpanel.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
					},
					{
						title: 'Resend & React Email',
						description: 'Resend & React Email',
						iconUrl: '/images/nodejs.png',
						link: 'https://www.nodejs.org',
						startYear: 2022,
					},
					{
						title: 'Google Maps',
						description: 'Google Maps',
						iconUrl: '/images/google-maps.png',
						link: 'https://www.google.com/maps',
						startYear: 2020,
					},
					{
						title: 'Mapbox',
						description: 'Mapbox',
						iconUrl: '/images/mapbox.png',
						link: 'https://www.mapbox.com/',
						startYear: 2020,
					},
				],
			},
			{
				title: 'Other Tools',
				description: 'Other Tools',
				splitColumns: true,
				technologies: [
					{
						title: 'VS Code',
						description: 'VS Code',
						iconUrl: '/images/vscode.png',
						link: 'https://www.nextjs.org',
						startYear: 2022,
					},
					{
						title: 'Linear',
						description: 'Linear',
						iconUrl: '/images/linear.png',
						link: 'https://www.linear.app',
						startYear: 2022,
					},
					{
						title: 'Jira',
						description: 'Jira',
						iconUrl: '/images/jira.png',
						link: 'https://www.atlassian.com/software/jira',
						startYear: 2022,
					},
					{
						title: 'Postman',
						description: 'Postman',
						iconUrl: '/images/postman.png',
						link: 'https://www.reactjs.org',
						startYear: 2022,
					},
					{
						title: 'HTTPie',
						description: 'HTTPie',
						iconUrl: '/images/httpie.png',
						link: 'https://www.vuejs.org',
						startYear: 2022,
					},
					{
						title: 'XCode',
						description: 'Express',
						iconUrl: '/images/express.png',
						link: 'https://www.expressjs.org',
						startYear: 2022,
					},
					{
						title: 'Warp Console',
						description: 'Warp Console',
						iconUrl: '/images/warp.png',
						link: 'https://www.nodejs.org',
						startYear: 2022,
					},
				],
			},
		],
	},
	{
		title: 'Design',
		description: 'Design',
		icon: <Frame size={16} color="#ffffff" />,
		groups: [
			{
				title: 'Graphic Design',
				description: 'Graphic Design',
				splitColumns: true,
				technologies: [
					{
						title: 'Figma',
						description: 'Figma',
						iconUrl: '/images/figma.png',
						link: 'https://www.intel.com',
						startYear: 2022,
					},
					{
						title: 'Adobe Illustrator',
						description: 'Adobe Illustrator',
						iconUrl: '/images/adobe-illustrator.png',
						link: 'https://www.adobe.com/products/illustrator.html',
						startYear: 2022,
					},
					{
						title: 'Autodesk Graphic',
						description: 'Autodesk Graphic',
						iconUrl: '/images/autodesk-graphic.png',
						link: 'https://www.autodesk.com/products/autocad-360/overview',
						startYear: 2022,
					},
					{
						title: 'Adobe Photoshop',
						description: 'Adobe Photoshop',
						iconUrl: '/images/adobe-photoshop.png',
						link: 'https://www.adobe.com/products/photoshop.html',
						startYear: 2022,
					},
				],
			},
			{
				title: 'Video Editing',
				description: 'Video Editing',
				splitColumns: true,
				technologies: [
					{
						title: 'Adobe Premiere Pro',
						description: 'Adobe Premiere Pro',
						iconUrl: '/images/adobe-premiere-pro.png',
						link: 'https://www.intel.com',
						startYear: 2022,
					},
					{
						title: 'Adobe After Effects',
						description: 'Adobe After Effects',
						iconUrl: '/images/adobe-after-effects.png',
						link: 'https://www.adobe.com/products/illustrator.html',
						startYear: 2022,
					},
					{
						title: 'Autodesk 3D Max',
						description: 'Autodesk 3D Max',
						iconUrl: '/images/autodesk-3d-max.png',
						link: 'https://www.autodesk.com/products/autocad-360/overview',
						startYear: 2022,
					},
					{
						title: 'Blender',
						description: 'Blender',
						iconUrl: '/images/blender.png',
						link: 'https://www.adobe.com/products/photoshop.html',
						startYear: 2022,
					},
				],
			},
		],
	},
];
